### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by JustinElst** [SynergiTech/laravel-twig#1]
While searching for a blade alternative for laravel frontend (closer to angular6 templates). we fount the twig bridge:
https://github.com/rcrowe/TwigBridge
And this 16 hour old repo.

I am curious what the state of this project is, and why you chose to make a different implementation.
Or am I wrong in thinking the two are similar. What are the pro's cons?

Anyway thanks for sharing the code.

**Comment by forestlovewood** [comment]
This project was created so we would be able to heavily modify the codebase under a different package name. You'd be correct in thinking that it is based on TwigBridge and shares a lot of code - we've upgraded the version of Twig, however, and stripped out some code.

I wouldn't recommend using the project in a production project at this point, however you're welcome to if it meets your needs - because it's a drop-in extension to provide Twig template compatibility, the core functionality is very unlikely to change. Unit tests and documentation will be added in the future.
